---
output: 
  html_document:
    theme: cosmo
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

$\\$

<center>## Age-Stratified SARS-CoV-2 Infection Fatality Rates in NYC:
<center>### January 28

Status: First draft uploaded to medRxiV! doi: https://doi.org/10.1101/2020.10.16.20214023 

SARS-CoV-2 Infection Fatality Rates for New York City
```{r message = FALSE, echo = FALSE}
library(tidyverse)
load("data_setup.rda")
IFRs <- readRDS("age_stratified_IFRs_raw.rds")
IFRs <- IFRs %>%
  group_by(age_class) %>% 
  mutate(sim = row_number()) %>% 
  ungroup() %>% 
  inner_join(prev_est_age_draws,
             by = c("sim", "age_class" = "age_class")) %>% 
  group_by(sim) %>% 
  summarise(ifr = weighted.mean(ifr, seropos * pop)) %>% 
  mutate(age_class = "all") %>% 
  select(ifr, age_class) %>% 
  rbind(IFRs) 

# Compute Bayesian p-values ----------------------------------------------------

ref_age <- "45-64"    # reference age class -- this used to be [20, 50)
ref_ifrs <- IFRs$ifr[IFRs$age_class == ref_age] # reference IFR posterior draws

IFR_pvals <- IFRs %>% 
  group_by(age_class) %>% 
  summarise(pval = computePval(ifrs, ref_ifrs)) %>% 
  mutate(pval = case_when(age_class == ref_age ~ as.double(NA), T ~ pval),
         pval_string = case_when(pval == 0 ~ "<0.001",
                                 is.na(pval) ~ "-",
                                 T ~ format(pval, digits = 2)))

IFR_stats <- 
  # Epi data
  age_epidata %>%
  group_by(age_class) %>% 
  arrange(desc(case_cumul)) %>% 
  select(case_cumul, death_cumul) %>% 
  slice(1) %>% ungroup() %>% 
  # Populations by age
  inner_join(age_popdata %>% select(age_class, total)) %>% 
  # Seroprevalence estimates
  inner_join(prev_est_age_draws %>% 
               group_by(age_class) %>% 
               summarise(sero.mean = mean(seropos),
                         sero.025 = quantile(seropos, 0.025),
                         sero.975 = quantile(seropos, 0.975))) %>% 
  mutate(seropop.mean = sero.mean * total,
         seropop.025 = sero.025 * total,
         seropop.975 = sero.975 * total) %>% 
  # IFR estimates
  inner_join(
    IFRs %>% 
      group_by(age_class) %>% 
      mutate(ifr = ifr*1e2) %>% 
      summarise(mean = mean(ifr),
                q025 = quantile(ifr, 0.025),
                q975 = quantile(ifr, 0.975))
  ) %>% 
  inner_join(IFR_pvals) %>% 
  group_by(age_class) %>% 
  mutate_at(vars(mean, q025, q975), 
            function(x) format(x, digits = 2)) %>% 
  mutate_at(vars(contains("seropop")), 
            function(x) 100*round(x/100)) %>% 
  ungroup() %>% 
  mutate(ifr = paste0(mean, " (", q025, "-", q975, ")"),
         seropop = paste0(format(seropop.mean, big.mark = ","),
                          " (", format(seropop.025, big.mark = ","), 
                          "-", 
                          format(seropop.975, big.mark = ","), ")"),
         age_class = factor(age_class, 
                            levels = age_classes[c(1, 2, 3, 4:length(age_classes))])) %>%
  arrange(age_class)

IFR_stats$age_class <- as.character(IFR_stats$age_class)
IFR_stats[1,1] <- "0-17 *"
IFR_stats[2,1] <- "18-44"
IFR_stats[3,1] <- "45-64"
IFR_stats[4,1] <- "65-74"
IFR_stats[5,1] <- "75+"

IFR_pvals <- IFR_stats %>% 
  select(age_class, seropop, death_cumul, ifr, pval_string) %>% 
  rename(`Age class` = age_class,
         `Estimated infected` = seropop,
         `Deaths` = death_cumul,
         IFR = ifr,
         `p-value` = pval_string) 

IFR_stats <- IFR_stats %>% 
  select(age_class, total, seropop, death_cumul, ifr) %>% 
  rename(`Age class` = age_class,
         Population = total,
         `Estimated infected` = seropop,
         `Deaths` = death_cumul,
         IFR = ifr)

knitr::kable(IFR_stats)
```


